### PR TITLE
#158: Added fields formatted_phone and phone to the To & From Models

### PR DESCRIPTION
**Pull request by dvanwinkle**
Ref: #158

### CODE REVIEW

**Comment by mozts2005** [comment]
Test Please

**Comment by dvanwinkle** [comment]
@mozts2005 Do you just mean write an integration test for it?

**Comment by mozts2005** [comment]
Yes, I would Like to see some level of automated testing
 integration or unit is up to you

**Comment by dvanwinkle** [comment]
@mozts2005 So, this one is a little interesting. For an integration test, I'd have to add a way to create voice tickets through this wrapper. It would be a great feature enhancement, but, it (IMO) is out of scope for the ticket. I can create a unit test to ensure that the JSON outputted by the classes (To & From) are as expected and vice versa (properties are populated via JSON).

Would this be acceptable?

**Comment by mozts2005** [comment]
Unit test would be just.

**Comment by dvanwinkle** [comment]
@mozts2005 Tests added. Let me know if you would like something different.

**Pull request merged**
