### PR TITLE
Fixed tests and new property for ticket comments

### PR DESCRIPTION
**Pull request by WinDrop**

### CODE REVIEW

**Comment by overanalyzer** [comment]
I'm trying to create tickets with HTML comments, which this commit seems intended to cover. But unless I'm missing something, it doesn't seem to have made it into a build yet — is that correct?

Is there a plan to add this into a new build?

Thanks!

**Comment by overanalyzer** [comment]
Hey @WinDrop and @mozts2005 — it doesn't seem like this commit has made it into a build ywt. 3.6.1 seems to still have HtmlBody as a private get instead of public.

Is there a plan for incorporating this commit into a build?

Thanks!
-Matthew

**Comment by mozts2005** [comment]
This will be released as part of the 3.6.2 release. you can it test this using the myget feed 
https://www.myget.org/feed/zendeskapi_v2_prerelease/package/nuget/ZendeskApi_v2v

**Comment by overanalyzer** [comment]
@mozts2005 great, thanks! I didn't know about the pre-release nuget, that's helpful. In my testing using downloaded source and a locally built DLL, HTML comments seem to work well with the new code change. Thanks for the heads up that 3.6.2 will include this change, I'll swap back to the nuget package when that's released. 

Thanks!

**Pull request merged**
