### PR TITLE
Add netstandard2.0 as target framework

### LINKED ISSUE #235: .net core support?
does it support .net core or any plan to support it?

### PR DESCRIPTION
**Pull request by mbp**
Problem compiles fine with netstandard2.0

This should fix #235

### CODE REVIEW

**Comment by austin94** [comment]
This would be very helpful for some of the more modern core applications! Any chance of this getting merged?

**Comment by mozts2005** [comment]
I am willing to so this. But I want to make sure the test will still pass please change the test project to be .net core. 

if they pass i will then merge this.

**Comment by mbp** [comment]
Done, passes locally

**Comment by freemstr** [comment]
Thank you
When do you think will 3.9.0 nuget package be available?
ZendeskApi_v2 is the last non-core reference I have and the above discussion is great news.

**Pull request merged**
