### PR TITLE
Int to long

### LINKED ISSUE #262: Need to change sectionid from int to long in article results
Bug: I have noticed that sectionids in zendesk are now longer that int32  and as such search results are getting a "JSON integer .... is too large or small for an Int32" parse error

Could you please update the sectionid in the below file to be a long instead of int
ZendeskApi_v2/src/ZendeskApi_v2/Models/Articles/Result.cs

You may need to update sectionid type in other parts of your model as well.

Thanks

### LINKED ISSUE #263: CreatePost() Exception
When attempting to add a post with `HelpCenter.Posts.CreatePost()` the following exception is thrown: "JSON integer 1234567897 is too large or small for an Int32. Path 'post.author_id', line 1, position 3823." It appears the post model object's AuthorID property is of type int but it is trying to use the Zendesk user ID which is long. 

Stack Trace:
"   at Newtonsoft.Json.JsonTextReader.ParseNumber(ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)\r\n   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)\r\n   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)\r\n   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)\r\n   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)\r\n   at ZendeskApi_v2.Core.RunRequest[T](String resource, String requestMethod, Object body, Nullable`1 timeout, String formKey)\r\n   at ZendeskApi_v2.Core.GenericPost[T](String resource, Object body)\r\n   at ZendeskApi_v2.Requests.HelpCenter.Posts.CreatePost(Post post)\r\n   at ZendeskForumPostImport.ForumService.ImportPosts() in c:\\Users\\Visual Studio 2015\\Projects\\ForumService.cs:line 66"

### PR DESCRIPTION
**Pull request by mozts2005**
Changed all public properties to from int to long per docs
https://developer.zendesk.com/rest_api/docs/core/introduction#id-integers
fixed #263, fixed #262

### CODE REVIEW

**Comment by mozts2005** [comment]
:white_check_mark: [Build ZendeskApi_v2 3.5.4-PullRequest264.5.build.122 completed](https://ci.appveyor.com/project/mozts2005/zendeskapi-v2/build/3.5.4-PullRequest264.5.build.122) (commit https://github.com/mozts2005/ZendeskApi_v2/commit/5c0d1a0b9b by @mozts2005)

**Comment by mozts2005** [comment]
:white_check_mark: [Build ZendeskApi_v2 3.5.4-PullRequest264.5.build.122 completed](https://ci.appveyor.com/project/mozts2005/zendeskapi-v2/build/3.5.4-PullRequest264.5.build.122) (commit https://github.com/mozts2005/ZendeskApi_v2/commit/5c0d1a0b9b by @mozts2005)

**Comment by mozts2005** [comment]
:white_check_mark: [Build ZendeskApi_v2 3.5.4-PullRequest264.6.build.122 completed](https://ci.appveyor.com/project/mozts2005/zendeskapi-v2/build/3.5.4-PullRequest264.6.build.122) (commit https://github.com/mozts2005/ZendeskApi_v2/commit/55b909d5ba by @mozts2005)

**Comment by bvillanueva-mdsol** [comment]
@mozts2005 Thank you so much for addressing this. We are currently using your library. We really appreciate the work your team is doing. Will this PR be released in a nuget very soon?
- Brent

**Comment by mozts2005** [comment]
@bvillanueva-mdsol  I think we can release this. I was hoping to get feedback that the changes didn't create more issues.

**Comment by bvillanueva-mdsol** [comment]
@mozts2005 Thanks for the info. We can help in testing. We can test the Zendesk ticket and articles part of the client. :)

**Comment by mozts2005** [comment]
@bvillanueva-mdsol Has been released to nuget.

**Comment by bvillanueva-mdsol** [comment]
Thanks @mozts2005 For the update!

**Pull request merged**
