### PR TITLE
Zendesk Voice amendments

### PR DESCRIPTION
**Pull request by WinDrop**
Deleted Historical Queue Activity as it's no longer supported by Zendesk. Added Current Queue Activity class and methods

### CODE REVIEW

**Comment by mozts2005** [comment]
This PR looks good to me. You just need to make the build work, and I will pull these changes in

**Comment by WinDrop** [comment]
Hi Elizabeth. Thanks for comment. I don't quite understand why the build fails. A full rebuild of the solution succeeds and I don't understand why build here on github would fail. I also cannot see any details of the failure. Do you mind pointing me in the right direction please?

**Comment by WinDrop** [comment]
Another question whilst here if you don't mind please. Every time I create a pull request it tries to merge all my previous contributions as well. Is that normal? I've only made a single commit since my last approved pull request. I'm sure I'm doing something wrong with github but not quite sure what :( Thanks

**Comment by WinDrop** [comment]
Ok, I think I know what happened. I haven't had a merge from master for a while so my branch has been out of date all this time. I've now merged all changes from master branch and will try to fix the build

**Comment by WinDrop** [comment]
Ok, all of my code is now building and running correctly. For some reason there are 19 tests (Not a single one written or touched by me) Which are failing. Now I'm wondering how have they ever been checked in?

**Pull request merged**
