### PR TITLE
get User related info #227

### PR DESCRIPTION
**Pull request by M3LiNdRu**
Implemented method for getting user related info

### CODE REVIEW

**Comment by mozts2005** [comment]
I am looking in to why the build is broken if I find that the issue is with your test or code I will let you know. But it don't think it is

**Comment by M3LiNdRu** [comment]
@mozts2005 I checked it before, the build is broken because the test data in some tests it's wrong. The users are expired or something like that.

I'll have a look if you don't mind

**Comment by mozts2005** [comment]
I don't at all mind if you can fix it please do

**Comment by mozts2005** [comment]
I have contacted Zendesk Support. It looks like to account that we use for unit testing has been disabled. They are looking into it and will let us know when this has been fixed.

**Comment by M3LiNdRu** [comment]
Thanks @mozts2005. Any news from Zendesk Support?

**Pull request merged**
