### PR TITLE
Implementing support for User Segments and removing dependencies to Access Policies

### PR DESCRIPTION
**Pull request by jmprovencher**
Updating the library to support the new user segments API from Zendesk since the Access Policies API will stop working on December 15th. All User Segments API functions have been implemented and tested by Unit Tests.

### CODE REVIEW

**Comment by jmprovencher** [comment]
@mozts2005 The tests that are failing are not related to my changes. They are failing with master also.

**Comment by mozts2005** [comment]
Yes I see that I am going to fix them. So we can get a clean build of your changes.

The only issue I see with your PR is the last commit has naming convention change and I would like that changed back. 

Other than that this good and I will get this moved in and tested so we can get the release out.

**Comment by jmprovencher** [comment]
Yeah I add some problems with the core.cs file with some added lines. I reverted the changes and pushed back. @mozts2005

**Comment by mozts2005** [comment]
to be more clear I was meaning more like
```C#
UserSegment user_segment
```
should be 
```C#
UserSegment userSegment
```

**Comment by jmprovencher** [comment]
For some reason when naming UserSegment userSegment, the serialized json would be

`{"userSegments": }` instead of `{"user_segments": }`

**Comment by jmprovencher** [comment]
For example `System.Net.WebException : The remote server returned an error: (400) Bad Request.Error content: Required parameter missing: user_segment 
 Resource String: help_center/user_segments.json  + 
 Body: {
  "UserSegment": {
    "name": "My Test User Segment Async",
    "user_type": "signed_in_users"
  }`

**Comment by jmprovencher** [comment]
@mozts2005 I fixed your request of naming convention.

**Pull request merged**
